//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStars.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Star
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Type is Required")]
        public string Type { get; set; }

        [Required(ErrorMessage = "Solar Mass is Required")]
        public decimal SolarMass { get; set; }

        public Nullable<decimal> ApparentMagnitude { get; set; }

        [Required(ErrorMessage = "Description is Required")]
        public string Info { get; set; }

        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Your name is Required")]
        public string AddedBy { get; set; }

        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }
    }
}
